import Nav from '../components/Nav/Nav';

import '../styles/global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <main style={{ marginTop: '90px' }}>{children}</main>
      </body>
    </html>
  );
}
